// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/Fedosin/manila-csi-operator/pkg/apis/manilacsi/v1alpha1.Manila":       schema_pkg_apis_manilacsi_v1alpha1_Manila(ref),
		"github.com/Fedosin/manila-csi-operator/pkg/apis/manilacsi/v1alpha1.ManilaSpec":   schema_pkg_apis_manilacsi_v1alpha1_ManilaSpec(ref),
		"github.com/Fedosin/manila-csi-operator/pkg/apis/manilacsi/v1alpha1.ManilaStatus": schema_pkg_apis_manilacsi_v1alpha1_ManilaStatus(ref),
	}
}

func schema_pkg_apis_manilacsi_v1alpha1_Manila(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Manila is the Schema for the manilas API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Fedosin/manila-csi-operator/pkg/apis/manilacsi/v1alpha1.ManilaSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Fedosin/manila-csi-operator/pkg/apis/manilacsi/v1alpha1.ManilaStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/Fedosin/manila-csi-operator/pkg/apis/manilacsi/v1alpha1.ManilaSpec", "github.com/Fedosin/manila-csi-operator/pkg/apis/manilacsi/v1alpha1.ManilaStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_manilacsi_v1alpha1_ManilaSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ManilaSpec defines the desired state of Manila",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_manilacsi_v1alpha1_ManilaStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ManilaStatus defines the observed state of Manila",
				Type:        []string{"object"},
			},
		},
	}
}
